// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 26a7bc28b054098e8d7400f7623bd594c8bf280a7d210a423ba89d6209fa5825

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "DSFR";

export const themeNames: ThemeName[] = ["DSFR"];

export type KcEnvName =
    | "DSFR_THEME_HOME_URL"
    | "DSFR_THEME_SERVICE_TITLE"
    | "DSFR_THEME_BRAND_TOP";

export const kcEnvNames: KcEnvName[] = [
    "DSFR_THEME_HOME_URL",
    "DSFR_THEME_SERVICE_TITLE",
    "DSFR_THEME_BRAND_TOP"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    DSFR_THEME_HOME_URL: "",
    DSFR_THEME_SERVICE_TITLE: "",
    DSFR_THEME_BRAND_TOP: "République<br/>Française"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    | import("./account/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));
export const KcAccountPage = lazy(() => import("./account/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                    case "account":
                        return <KcAccountPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
